### ISSUE TITLE
Be'ware: this extension brings adwares to spy on you

### ISSUE THREAD

**Issue by jesobreira** [AminaG/Webpage-Screenshot#19]
This plugin (at least the version from Chrome webstore) is FULL of adwares/crapwares!

After installing it I could see many notifications about blocked domains from Malwarebytes, as well as JollyWallet bar in every e-commerce site I visited. How can I guarantee you weren't stealing my credit cards data? It fits a legal action, you know it.

For all users: remove this extension right now from your browser, read every line of the source code and build the extension by yourself.

Thanks goodness it was removed from [Chrome WebStore](https://chrome.google.com/webstore/detail/webpage-screenshot/ckibcdccnfeookdmbahgiakhnjcddpki).

And just before @AminaG says that "the extension I'm talking about isn't this one", well...  The name is the same, okay. But the logo is the same too... well, ok. The interface is the same... okay... But the [website](http://www.webpagescreenshot.info/) is also the same! D'oh!

Or maybe you keep two similar extensions, and one of them is a spyware and this one is really free of malwares? Well, only a code audit can tell it.

More info:
https://www.reddit.com/r/techsupport/comments/3e2c5o/weird_chrome_malware_that_i_cant_get_rid_of/
http://www.scmagazineuk.com/data-scraping-chrome-extension-steals-more-than-a-million-users-data/article/407892/

Everybody adviced? Now, feel free to close this issue, as you always do, mr. @AminaG !

**Comment by AminaG** [comment]
Please try to contact with the man behind the extension you talking about. He  made lot of damage to this extensin.  If someone forking this extension, it is not my fault.

Sorry.
