### ISSUE TITLE
Why has your plugin been removed from Chrome Web Store?

### ISSUE THREAD

**Issue by parleer** [AminaG/Webpage-Screenshot#29]
I received a popup notice from Chrome that the WebpageScreenshot plugin had been automatically removed. What's up? Also, do you have any idea how to prevent Google from displaying this popup every time I open a new browser?

**Comment by shirepirate** [comment]
http://arstechnica.com/security/2015/04/chrome-extension-collects-browsing-data-uses-it-for-marketing/
https://heimdalsecurity.com/blog/webpage-screenshot-leaks-private-data-million-users/

**Comment by AminaG** [comment]
This link not related to this extension.

**Comment by shirepirate** [comment]
you are mentioned by name in the article. also it's clear from the screenshots it is the same extension (there are also many more articles about it). it was also removed from google play store once, though it is back

**Comment by AminaG** [comment]
It's open source extension. Anyone can fork the project inject code, and upload it.

**Comment by shirepirate** [comment]
from the same chrome web store developer account? nice try :)

**Comment by shirepirate** [comment]
![image](https://cloud.githubusercontent.com/assets/2275004/12973674/0d7672ee-d07c-11e5-811c-49a5cf5da87d.png)
![image2](https://cloud.githubusercontent.com/assets/2275004/12973679/15a26c52-d07c-11e5-93a1-9ad6c9d63b7d.png)
