### ISSUE TITLE
Typo on Chrome Web Store description

### ISSUE THREAD

**Issue by denilsonsa** [AminaG/Webpage-Screenshot#3]
At the [Chrome Web Store description](https://chrome.google.com/webstore/detail/webpage-screenshot/akgpcdalpfphjmfifkmfbpdmgdmeeaeo), the URL for the source-code is incorrect. It says:

    【Source Code】
    https://www.github.com/AminaG/Webpage-Screensbot

But it should be:

    https://github.com/AminaG/Webpage-Screenshot/

Screens**b**ot → Screens**h**ot

**Comment by AminaG** [comment]
Fixed. Thank you.
