### ISSUE TITLE
Humble suggestion: no more redirecting, please!

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [AminaG/Webpage-Screenshot#5]
Hi developers of webpage screenshot:
 
I have used this extension for a while and it is really cool. I love it. I want to pay for it for some amount, but I didn't coz I don't have paypal.

Now I see the extension is violating Google Chrome APP Strore Regulation according to Google, and is removed from the store, but I don't know why, and I continued to use it. However, it began to redirect me to strange pages, and I can see a strange tool bar atop of some web pages I explored, named jollywallet or something, where also figured that the ad is sponsored by webpage screenshot. And, I noticed your developer's page is financed by a website named Remarketing, and I have been redirected to the page of this company, too. So, now I know why it is reported by extension users.

Please, guys, I appreciate your effort and great work and I am willing to pay for your work. But I cannot accept the doing of your financier. I can donate, even if I don't have paypal, maybe it is not enough for u to support this extension, but, please tell your partners to stop this. My words may not matter to you, but I must tell you this. So if you have new works done, tell me and I will support it.

Bye.

**Comment by AminaG** [comment]
The extension you talking about not relating to this extension.
This extension is open-source extension, without any malware inside.

They just have the same name.

If you want to install this extension please go to:
https://chrome.google.com/webstore/detail/webpage-screenshot/akgpcdalpfphjmfifkmfbpdmgdmeeaeo
