### ISSUE TITLE
why this extension adding a lot of advertising javascripts to webpage?

### ISSUE THREAD

**Issue by leetom** [AminaG/Webpage-Screenshot#6]
I have installed this extension for a very long time, but recently I got a lot of ads pop-ups.

I checked all the extensions, after I disabled this, the javascripts were gone. After I enabled this one, they came back.

The javascripts are from api.jollywallet.com, foxydeal.com, eshopcomp etc. Are they sponsors' links or my browser is hijacked?

**Comment by D-Alex** [comment]
This extension is male ware. I would delete it.

http://www.scmagazineuk.com/data-scraping-chrome-extension-steals-more-than-a-million-users-data/article/407892/

**Comment by AminaG** [comment]
The extension you talking about not relating to this extension.
This extension is open-source extension, without any malware inside.

They just have the same name.

If you want to install this extension please go to:
https://chrome.google.com/webstore/detail/webpage-screenshot/akgpcdalpfphjmfifkmfbpdmgdmeeaeo
